#!/usr/bin/env node

/**
 * Example: Express.js application with DrTrace integration
 * Generated by: npx drtrace init
 */

import express, { Request, Response, NextFunction } from "express";
import { promises as fs } from "fs";
import path from "path";

// In a real implementation, these would be imported from drtrace
// For now, we show the integration pattern

const app = express();
const port = 3000;

// Middleware to log requests
app.use((req: Request, res: Response, next: NextFunction) => {
  const start = Date.now();
  
  res.on("finish", () => {
    const duration = Date.now() - start;
    console.log(`${req.method} ${req.path} ${res.statusCode} ${duration}ms`);
  });
  
  next();
});

// Parse JSON
app.use(express.json());

// Health check endpoint
app.get("/api/health", (req: Request, res: Response) => {
  console.log("Health check requested");
  res.json({
    status: "healthy",
    service: "example-app-js",
    timestamp: new Date().toISOString(),
  });
});

// Get user by ID
app.get("/api/users/:userId", (req: Request, res: Response) => {
  const userId = parseInt(req.params.userId, 10);
  
  console.log(`Fetching user ${userId}`);
  
  if (isNaN(userId) || userId < 0) {
    console.error(`Invalid user ID: ${userId}`);
    return res.status(400).json({ error: "Invalid user ID" });
  }
  
  if (userId > 10000) {
    console.warn(`User ID ${userId} not found`);
    return res.status(404).json({ error: "User not found" });
  }
  
  console.log(`Successfully retrieved user ${userId}`);
  return res.json({
    id: userId,
    name: `User ${userId}`,
    email: `user${userId}@example.com`,
  });
});

// Process request with error handling
app.post("/api/process", (req: Request, res: Response) => {
  try {
    const data = req.body;
    console.log(`Processing request with data:`, data);
    
    if (!data || typeof data.value === "undefined") {
      console.error("Missing required field: value");
      return res.status(400).json({ error: "Missing required field" });
    }
    
    const value = parseFloat(data.value);
    
    if (value === 0) {
      console.error("Division by zero error");
      return res.status(400).json({ error: "Cannot divide by zero" });
    }
    
    const result = 100 / value;
    console.log(`Successfully processed request, result: ${result}`);
    return res.json({ result });
    
  } catch (error) {
    console.error(`Unexpected error processing request:`, error);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// 404 handler
app.use((req: Request, res: Response) => {
  console.warn(`Endpoint not found: ${req.path}`);
  res.status(404).json({ error: "Not found" });
});

// Error handler
app.use(
  (
    error: any,
    req: Request,
    res: Response,
    next: NextFunction
  ) => {
    console.error(`Internal server error:`, error);
    res.status(500).json({ error: "Internal server error" });
  }
);

// Start server
app.listen(port, () => {
  console.log(`Example Express application with DrTrace running on http://localhost:${port}`);
});
