"""
Example: Python Flask application with DrTrace integration
Generated by: drtrace init-project
"""

import logging
from pathlib import Path
from flask import Flask, jsonify, request

# Import DrTrace configuration and logging setup
from drtrace_client import setup_logging, ClientConfig
from drtrace_service.cli.config_schema import ConfigSchema

# Initialize Flask app
app = Flask(__name__)

# Load DrTrace configuration from _drtrace/config.json
config_path = Path("_drtrace/config.json")
if config_path.exists():
    drtrace_config = ConfigSchema.load(config_path)
    
    # Set up DrTrace logging with loaded configuration
    client_config = ClientConfig(
        application_id=drtrace_config.get("application_id", "example-app"),
        daemon_url=drtrace_config.get("daemon_url", "http://localhost:8001"),
        enabled=drtrace_config.get("enabled", True)
    )
    setup_logging(client_config)
else:
    # Fallback configuration if _drtrace/config.json doesn't exist
    setup_logging(ClientConfig(
        application_id="example-app",
        daemon_url="http://localhost:8001",
        enabled=True
    ))

# Get logger
logger = logging.getLogger(__name__)


@app.route("/api/health", methods=["GET"])
def health():
    """Health check endpoint"""
    logger.info("Health check requested")
    return jsonify({"status": "healthy", "service": "example-app"})


@app.route("/api/users/<int:user_id>", methods=["GET"])
def get_user(user_id):
    """
    Get user by ID.
    Demonstrates error logging with DrTrace.
    """
    logger.info(f"Fetching user {user_id}")
    
    if user_id < 0:
        logger.error(f"Invalid user ID: {user_id}")
        return jsonify({"error": "Invalid user ID"}), 400
    
    # Simulate user lookup
    if user_id > 10000:
        logger.warning(f"User ID {user_id} not found")
        return jsonify({"error": "User not found"}), 404
    
    logger.info(f"Successfully retrieved user {user_id}")
    return jsonify({
        "id": user_id,
        "name": f"User {user_id}",
        "email": f"user{user_id}@example.com"
    })


@app.route("/api/process", methods=["POST"])
def process_request():
    """
    Process a request and demonstrate exception handling.
    """
    try:
        data = request.get_json()
        logger.info(f"Processing request with data: {data}")
        
        if not data or "value" not in data:
            logger.error("Missing required field: value")
            return jsonify({"error": "Missing required field"}), 400
        
        value = data["value"]
        result = 100 / value  # Could raise ZeroDivisionError
        
        logger.info(f"Successfully processed request, result: {result}")
        return jsonify({"result": result})
        
    except ZeroDivisionError as e:
        logger.error(f"Division by zero error: {e}", exc_info=True)
        return jsonify({"error": "Cannot divide by zero"}), 400
    except Exception as e:
        logger.error(f"Unexpected error processing request: {e}", exc_info=True)
        return jsonify({"error": "Internal server error"}), 500


@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    logger.warning(f"Endpoint not found: {request.path}")
    return jsonify({"error": "Not found"}), 404


@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors"""
    logger.error(f"Internal server error: {error}", exc_info=True)
    return jsonify({"error": "Internal server error"}), 500


if __name__ == "__main__":
    logger.info("Starting example Flask application with DrTrace")
    app.run(debug=True, host="127.0.0.1", port=5000)
